language: node_js
node_js:
  - 14

services:
  - mongodb

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cracklib-runtime python3-dev libcrack2-dev
  - npm install

script:
  - npm run lint
