version: '2.1'

services:
  db:
    image: mongo:6-focal
    volumes:
      - ./db:/srv/db:rw
  dev:
    image: unocha/nodejs:18-alpine
    volumes:
      - .:/srv/www:rw
    ports:
      - 0.0.0.0:3000:3000
    environment:
      NODE_ENV: local
      ROOT_URL: http://api.hid.vm:3000
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER: ''
      SMTP_PASS: ''
      APP_URL: http://app.hid.vm
      COOKIE_PASSWORD: 6*a!_5;1:|7~+%5**WdS:^;X%PN||~:_:_R
      WKHTMLTOPDF_HOST: pdf.contactsid.vm
      WKHTMLTOPDF_PORT: 3000
  mailhog:
    image: mailhog/mailhog
    ports:
      - 0.0.0.0:8025:8025
