db:
  image: unocha/alpine-mongo
  volumes:
    - ./db:/srv/db
  environment:
    DNSDOCK_NAME: db
    DNSDOCK_IMAGE: hid
dev:
  image: unocha/alpine-nodejs:201610.npm3
  volumes:
    - .:/srv/www
  links:
    - db
  environment:
    DNSDOCK_NAME: api
    DNSDOCK_IMAGE: hid
    PORT: 80
    NODE_ENV: local
    ROOT_URL: http://api.hid.vm
    SMTP_HOST: app.mailhog.vm
    SMTP_PORT: 1025
    SMTP_USER: humanitarianid
    SMTP_PASS: smtp_password
    APP_URL: http://app.hid.vm
    COOKIE_PASSWORD: 6*a!_5;1:|7~+%5**WdS:^;X%PN||~:_:_R
test:
  image: unocha/alpine-nodejs:201610.npm3
  volumes:
   - .:/srv/www
  links:
   - db
  environment:
    DNSDOCK_NAME: apitest
    DNSDOCK_IMAGE: hid
    PORT: 80
    NODE_ENV: testing
    ROOT_URL: http://apitest.hid.vm
    SMTP_HOST: app.mailhog.vm
    SMTP_PORT: 1025
    SMTP_USER: humanitarianid
    SMTP_PASS: smtp_password
    APP_URL: http://app.hid.vm
    COOKIE_PASSWORD: 6*a!_5;1:|7~+%5**WdS:^;X%PN||~:_:_R
