version: "2.1"
services:
  db:
    image: unocha/mongo:4.0.5
    volumes:
      - ./data:/srv
      - ./db:/srv/db
      - .:/srv/www
    environment:
      DNSDOCK_NAME: db
      DNSDOCK_IMAGE: hid
    hostname: db
    networks:
      service:
        aliases:
          - db
          - db.hid.vm

  dev:
    image: unocha/nodejs:10.14.2
    volumes:
      - .:/srv/www
    links:
      - db
    environment:
      DNSDOCK_NAME: api
      DNSDOCK_IMAGE: hid
      PORT: 80
      NODE_ENV: local
      ROOT_URL: http://api.hid.vm
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USER: jeanette.senger60@ethereal.email
      SMTP_PASS: 7sJmaG2sf5a8r6VyJS
      APP_URL: http://app.hid.vm
      COOKIE_PASSWORD: 6*a!_5;1:|7~+%5**WdS:^;X%PN||~:_:_R
      V1_PROFILES_CLIENT_ID: clientid
      V1_PROFILES_CLIENT_SECRET: clientsecret
      WKHTMLTOPDF_HOST: pdf.contactsid.vm
      WKHTMLTOPDF_PORT: 3000
    hostname: hidapi
    networks:
      service:
        aliases:
          - hidapi
          - api.hid.vm
    expose:
      - 80


networks:
  service:
    external:
      name: hpcservice_service

#test:
#  image: unocha/alpine-nodejs:201610.npm3
#  volumes:
#   - .:/srv/www
#  links:
#   - db
#  environment:
#    DNSDOCK_NAME: apitest
#    DNSDOCK_IMAGE: hid
#    PORT: 80
#    NODE_ENV: testing
#    ROOT_URL: http://apitest.hid.vm
#    SMTP_HOST: app.mailhog.vm
#    SMTP_PORT: 1025
#    SMTP_USER: humanitarianid
#    SMTP_PASS: smtp_password
#    APP_URL: http://app.hid.vm
#    COOKIE_PASSWORD: 6*a!_5;1:|7~+%5**WdS:^;X%PN||~:_:_R
