openapi: 3.0.3
x-api-id: hid-api
info:
  version: 3.0.0-dev
  title: HID API
  license:
    name: Apache-2.0
servers:
  - url: 'http://api.hid.vm:3000/api/v3'
    description: Localhost server. For your own debugging.
  - url: 'https://dev.api-humanitarian-id.ahconu.org/api/v3'
    description: Dev server. For use by UNOCHA developers.
  - url: 'https://api.humanitarian.id/api/v3'
    description: Production server. For use by HID Integration Partners.
tags:
  - name: auth
    description: Methods related to authentication
  - name: user
    description: Methods related to users
  - name: client
    description: Methods related to oauth clients
  - name: totp
    description: Methods related to 2-factor authentication
components:
  securitySchemes:
    authToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Auth:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    JWT:
      type: object
      properties:
        token:
          type: string
    User:
      type: object
      properties:
        _id:
          type: string
          description: User unique ID
        id:
          type: string
          description: Shortcut to the user ID
        deleted:
          type: boolean
          description: Whether the user is active or not
        email:
          type: string
          description: The user primary email
        email_verified:
          type: string
          description: Whether the user primary email is verified
        emailsVisibility:
          type: string
          description: Who can view this user emails
        expires:
          type: string
          format: date-time
          description: When this user account expires (set to the past if it does not)
        family_name:
          type: string
          description: The user family name
        given_name:
          type: string
          description: The user given name
        isManager:
          type: boolean
          description: Whether the user is a global manager
        is_admin:
          type: boolean
          description: Whether the user is an admin
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
security:
  - authToken: []
paths:
  /jsonwebtoken:
    post:
      tags:
        - auth
      summary: Generate a jsonwebtoken
      requestBody:
        description: User email and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: The json web token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
        '400':
          description: Bad request. Missing email and/or password
        '401':
          description: Wrong email and/or password
        '429':
          description: >-
            The account was locked for 5 minutes because there were more than 5
            unsuccessful login attempts within the last 5 minutes
      security: []
    get:
      tags:
        - auth
      summary: Retrieve the JWTs of the current user
      responses:
        '200':
          description: >-
            Array of all JWTs for the current user, including blacklisted
            tokens.
    delete:
      tags:
        - auth
      summary: Blacklists a JWT for the current user
      responses:
        '200':
          description: JWT was successfully blacklisted
        '400':
          description: Missing token
        '403':
          description: Could not blacklist this token because you did not generate it
  /user:
    post:
      tags:
        - user
      summary: Create a new user
      requestBody:
        description: Required parameters to create a user.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                family_name:
                  type: string
                  required: true
                given_name:
                  type: string
                  required: true
                app_verify_url:
                  type: string
                  required: true
                  description: Should correspond to the endpoint you are interacting with.
      responses:
        '200':
          description: User was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request. Missing required parameters.
        '403':
          description: Forbidden. Your account is not allowed to create users.
      security: []

