openapi: 3.0.3
x-api-id: hid-api
info:
  version: 3.0.0-dev
  title: HID API
  license:
    name: Apache-2.0

servers:
  - url: 'https://dev.api-humanitarian-id.ahconu.org/api/v3'
    description: Dev server. For use by UNOCHA developers.
  - url: 'https://api.humanitarian.id/api/v3'
    description: Production server. For use by HID Integration Partners.

tags:
  - name: 'auth'
    description: 'Methods related to authentication'
  - name: 'user'
    description: 'Methods related to users'
  - name: 'client'
    description: 'Methods related to oauth clients'
  - name: 'totp'
    description: 'Methods related to 2-factor authentication'

components:
  securitySchemes:
    authToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Auth:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    JWT:
      type: object
      properties:
        token:
          type: string
    User:
      type: object
      properties:
        _id:
          type: string
          description: 'User unique ID'
        id:
          type: string
          description: 'Shortcut to the user ID'
        deleted:
          type: boolean
          description: 'Whether the user is active or not'
        email:
          type: string
          description: 'The user primary email'
        email_verified:
          type: string
          description: 'Whether the user primary email is verified'
        emailsVisibility:
          type: string
          description: 'Who can view this user emails'
        expires:
          type: string
          format: date-time
          description: 'When this user account expires (set to the past if it does not)'
        family_name:
          type: string
          description: 'The user family name'
        given_name:
          type: string
          description: 'The user given name'
        isManager:
          type: boolean
          description: 'Whether the user is a global manager'
        is_admin:
          type: boolean
          description: 'Whether the user is an admin'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

# Applying Auth token requirement to our entire API.
#
# @see https://swagger.io/docs/specification/authentication/bearer-authentication/
#
# To remove security requirements for a particular API method, set `security` to
# an empty array on that particular method. See `POST /jsonwebtoken` for an
# example within our codebase.
#
# @see https://stackoverflow.com/a/29020676
security:
  - authToken: []
