openapi: 3.0.3
x-api-id: hid-api
info:
  version: 3.0.0-dev
  title: HID API
  license:
    name: Apache-2.0
host: api.humanitarian.id
basePath: /api/v3
schemes:
  - https
servers:
  - url: 'https://api.humanitarian.id/api/v3'
    description: Production server. For use by HID Integration Partners.
  - url: 'https://dev.api-humanitarian-id.ahconu.org/api/v3'
    description: Dev server. For use by UNOCHA developers.
